### ISSUE TITLE
error while truffle unbox   

### ISSUE THREAD

**Issue by shsunmoonlee** [adrianmcli/truffle-next#26]
Seunghuns-MBP:truffle-nextjs seunghunlee$ truffle unbox adrianmcli/truffle-next
Downloading...
Unpacking...
Setting up...
Error: Command failed: cd client && npm install && npm run link-contracts
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'minizlib'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seunghunlee/.npm/_logs/2018-04-13T11_22_24_183Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by adrianmcli** [comment]
I am not able to reproduce.

@SeunghunSunmoonLee what version of Node and NPM are you running?

> npm ERR! Cannot find module 'minizlib'

This [issue](https://github.com/tj/n/issues/453) seems to indicate that there's something wrong with your Node.js or NPM installation.

**Comment by SeunghunSunmoonLee** [comment]
Seunghuns-MBP:truffle-nextjs seunghunlee$ node -v
v8.9.4
Seunghuns-MBP:truffle-nextjs seunghunlee$ npm -v
5.6.0

**Comment by adrianmcli** [comment]
Have you tried reinstalling node?
