### ISSUE TITLE
npm error while installing truffle-next in windows

### ISSUE THREAD

**Issue by emharsha1812** [adrianmcli/truffle-next#40]
I recently thought of working on a project using truffle and next-js so wanted to install the truffle-next box
However, I encountered some issues, a big list of npm errors

I am copy-pasting the entire list of errors below

× Setting up box
Unbox failed!
× Setting up box
Unbox failed!
Error: Command failed: cd client && npm install && npm run link-contracts
npm ERR! code 128
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\harsh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\harsh\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 128
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/gulpjs/gulp.git
npm ERR! npm ERR! git@github.com: Permission denied (publickey).
npm ERR! npm ERR! fatal: Could not read from remote repository.
npm ERR! npm ERR!
npm ERR! npm ERR! Please make sure you have the correct access rights
npm ERR! npm ERR! and the repository exists.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\harsh\AppData\Local\npm-cache\_logs\2022-02-06T06_56_50_418Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\harsh\AppData\Local\npm-cache\_logs\2022-02-06T06_56_52_199Z-debug.log

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.installBoxDependencies (C:\Users\harsh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\unbox.js:139:1)
    at Object.setUpBox (C:\Users\harsh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\index.js:66:1)
    at C:\Users\harsh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\harsh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:5:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.32 (core: 5.4.32)
Node v16.13.2

I am using Windows 11, along with the version of Node and Truffle as specified above
Does anyone have a resolve to this issue?

**Comment by wiredmatt** [comment]
I'm having the same problem using Fedora, so it's not Windows related. I tried different node version but got no luck.

**Comment by vishalcs106** [comment]
Problem persists in mac as well, any solution?

**Comment by saricden** [comment]
Same issue on Ubuntu.

**Comment by thetwosents** [comment]
Anyone want to try to contribute on this? Happy to help.

**Comment by denny999222** [comment]
The issue here I believe has to do with the older packages being used for this truffle box. React, Next, and Web3 are outdated. I've fixed the issue by upgrading all the dependencies. 

Go inside your client folder:
`cd client`

then

```
npm install web3@latest
npm install react@latest react-dom@latest
npm install next@latest
```

This is what fixed it for me. Hopefully works for you guys

**Comment by denny999222** [comment]
The unbox is all outdated. I just made a truffle and nextjs project manually.
```
npx create-next-app@latest
cd example-project
truffle init
```
